version: "3.9"

services:
  ros-melodic-cuda11.0.3:
    image: thecanadianroot/opencv-cuda:ubuntu18.04-cuda11.0.3-opencv3.4.14-rosmelodic
    build:
      context: .
      dockerfile: Dockerfile.ros-melodic
      args:
        - CUDA=11.3.1
        - UBUNTU=18.04
        - OPENCV=3.4.14

  ros-melodic-cuda11.3.1:
    image: thecanadianroot/opencv-cuda:ubuntu18.04-cuda11.3.1-opencv3.4.14-rosmelodic
    build:
      context: .
      dockerfile: Dockerfile.ros-melodic
      args:
        - CUDA=11.3.1
        - UBUNTU=18.04
        - OPENCV=3.4.14

  ros-noetic-cuda11.3.1:
    image: thecanadianroot/opencv-cuda:ubuntu20.04-cuda11.3.1-opencv4.5.2-rosnoetic
    build:
      context: .
      dockerfile: Dockerfile.ros-noetic
      args:
        - CUDA=11.3.1
        - UBUNTU=20.04
        - OPENCV=4.5.2